/**
 * Plugin indexability for Google (Bing is unaffected).
 *
 * EN: indexable if stars>=10 OR EN/ZH path in GSC 90d OR Bing click whitelist.
 * ZH: indexable if ZH path in Bing click whitelist OR GSC 90d whitelist.
 *
 * Non-indexable plugin pages emit <meta name="googlebot" content="noindex, follow">
 * (NOT name="robots"), so Bing keeps crawling them.
 *
 * Whitelist path keys are normalized: apex host, trailing slash, no query.
 * Source files: src/data/{gsc,bing}-whitelist.json and indexable-plugins.json
 * (regenerated by scripts/build-index-whitelist.py from seo-expert/raw3/).
 */
import plugins from '../data/plugins.json';
import indexable from '../data/indexable-plugins.json';

const enSet = new Set(indexable.en);
const zhSet = new Set(indexable.zh);

export function isPluginIndexable(slug, lang = 'en') {
  return lang === 'zh' ? zhSet.has(slug) : enSet.has(slug);
}

/** Demote README headings one level (h1→h2 … h5→h6) so the page keeps a single h1. */
export function demoteReadmeHeadings(html) {
  if (!html) return '';
  let out = html;
  for (let n = 5; n >= 1; n--) {
    const reOpen = new RegExp(`<h${n}(\\s|>)`, 'gi');
    const reClose = new RegExp(`</h${n}>`, 'gi');
    out = out.replace(reOpen, `<h${n + 1}$1`).replace(reClose, `</h${n + 1}>`);
  }
  return out;
}

export function allPluginsFlat() {
  return Object.entries(plugins).flatMap(([cat, items]) =>
    items.map((p) => ({ ...p, cat, slug: p.slug ?? p.name })),
  );
}

export const INDEXABLE_COUNTS = indexable.counts;
